### ISSUE TITLE
Query returning empty string("") for a boolean property, when the property is missing and no default value is set

### ISSUE THREAD

**Issue by Subhajit97** [turbot/steampipe#141] opened 2021-02-05 11:16 UTC
`Column definition`
```
{
	Name:        "log_config_enable",
	Description: "Specifies whether to enable logging for the load balancer traffic served by this backend service, or not.",
	Type:        proto.ColumnType_BOOL,
	Transform:   transform.FromField("LogConfig.Enable"),
},
```
the API response doesn’t contain the property `LogConfig.Enable` and no Default value is set for this column
When running the query I am getting value of this field as
```
"log_config_enable": "",
```

`branch`: `issue-80` (https://github.com/turbot/steampipe-plugin-gcp/pull/82)

**Comment by kaidaguerre** [comment] 2021-02-09 17:54
OK so what is happening here is this: the value is being returned as null (it is coming as null rather than `false` - the zero value of bool - as the property path for the column is `LogConfig.Enable`, and the `LogConfig.Enable` is null so we retrieve a null value for`log_config_enable`)

steampipe displays currently defaults to displaying null as an empty string

in table mode this looks as follows
```
+------------------------------------+-------------------+-------------+
| name                               | log_config_enable | project     |
+------------------------------------+-------------------+-------------+
| turbot-test-20200125-create-update |                   | pikachu-aaa |
+------------------------------------+-------------------+-------------+
```
in CSV mode it looks like this
```
[
 {
  "log_config_enable": "",
  "name": "turbot-test-20200125-create-update",
  "project": "pikachu-aaa"
 }
]
```

**Comment by kaidaguerre** [comment] 2021-02-22 09:59
expected behaviour - closing.

Have updated steampipe to display null as <null> (c1a62af8c239d1d9f144cf86394a9e026b6be702)

**Closed by kaidaguerre** 2021-02-22 09:59 UTC
Labels: bug, triage
