### ISSUE TITLE
Are the "plugin.stdio: received EOF" log messages needed?

### ISSUE THREAD

**Issue by e-gineer** [turbot/steampipe#316] opened 2021-03-19 19:11 UTC
**Describe the bug**

Steampipe shutdown creates a large batch (one per plugin) of log warnings. Are these important, or do they just look scary? Can they be removed?

```
2021-03-19 15:03:30.504 EDT [93434] LOG:  background worker "logical replication launcher" (PID 93442) exited with exit code 1
2021-03-19T15:03:30.506-0400 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
...
2021-03-19T15:03:30.554-0400 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-03-19 15:03:30.561 EDT [93438] LOG:  shutting down
```

**Steampipe version (`steampipe -v`)**

v0.3.0

**To reproduce**

Run steampipe, shutdown.

**Expected behavior**

Small number of appropriate log messages.

**Additional context**

None

**Comment by kaidaguerre** [comment] 2023-09-12 13:56
duplicate of [EOF](https://github.com/turbot/steampipe/issues/2234)

**Closed by kaidaguerre** 2023-09-12 13:56 UTC
Labels: bug, logging
