### ISSUE TITLE
`steampipe mod install` should not succeed if any dependent mod's `require` section is not satisfied

### ISSUE THREAD

**Issue by cbruno10** [turbot/steampipe#3277] opened 2023-03-28 17:51 UTC
**Describe the bug**
If I have mod A that has mod B as a dependency, and mod B has a CLI and/or plugin requirement that my env doesn't meet, I can still run `steampipe mod install` in mod's A directory and the install will complete.

**Steampipe version (`steampipe -v`)**
v0.19.3

**To reproduce**
See description above

**Expected behavior**
The install command should fail and tell me why

**Additional context**

**Comment by kaidaguerre** [comment] 2023-04-06 10:47
duplicate of https://github.com/turbot/steampipe/issues/3041

**Closed** 2023-04-06 10:51 UTC
Labels: bug, mod install
