### ISSUE TITLE
Occasionally unable to start Steampipe Service with "dial error (dial tcp [::1]:9193: connect: cannot assign requested address" error

### ISSUE THREAD

**Issue by vhadianto** [turbot/steampipe#2949] opened 2023-01-06 03:52 UTC
**Describe the bug**

We occasionally see the following error when starting Steampipe service:

```
Steampipe Start Service v1
Steampipe service is not running.
Error: retryable: failed to connect to `host=localhost user=root database=postgres`: dial error (dial tcp [::1]:9193: connect: cannot assign requested address)
```

There's nothing in plugin log.

This is an excerpt of the database log:

```
$ cat database-2023-01-05.csv 
2023-01-05 10:13:06.135 UTC,,,170,,63b6a2b1.aa,1,,2023-01-05 10:13:05 UTC,,0,LOG,00000,"ending log output to stderr",,"Future log output will go to log destination ""csvlog"".",,,,,,,"steampipe","postmaster",,0
2023-01-05 10:13:06.135 UTC,,,170,,63b6a2b1.aa,2,,2023-01-05 10:13:05 UTC,,0,LOG,00000,"starting PostgreSQL 14.2 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4, 64-bit",,,,,,,,,"steampipe","postmaster",,0
2023-01-05 10:13:06.135 UTC,,,170,,63b6a2b1.aa,3,,2023-01-05 10:13:05 UTC,,0,LOG,00000,"listening on IPv4 address ""127.0.0.1"", port 9193",,,,,,,,,"steampipe","postmaster",,0
2023-01-05 10:13:06.135 UTC,,,170,,63b6a2b1.aa,4,,2023-01-05 10:13:05 UTC,,0,LOG,XX000,"could not bind IPv6 address ""::1"": Cannot assign requested address",,,,,,,,,"steampipe","postmaster",,0
2023-01-05 10:13:06.269 UTC,,,170,,63b6a2b1.aa,5,,2023-01-05 10:13:05 UTC,,0,LOG,00000,"listening on Unix socket ""/tmp/.s.PGSQL.9193""",,,,,,,,,"steampipe","postmaster",,0
2023-01-05 10:13:06.450 UTC,,,173,"127.0.0.1:39222",63b6a2b2.ad,1,"",2023-01-05 10:13:06 UTC,,0,LOG,00000,"connection received: host=127.0.0.1 port=39222",,,,,,,,,"steampipe","not initialized",,0
2023-01-05 10:13:06.450 UTC,"root","postgres",173,"127.0.0.1:39222",63b6a2b2.ad,2,"",2023-01-05 10:13:06 UTC,,0,FATAL,57P03,"the database system is starting up",,,,,,,,,"steampipe","client backend",,0
2023-01-05 10:13:06.450 UTC,,,172,,63b6a2b2.ac,1,,2023-01-05 10:13:06 UTC,,0,LOG,00000,"database system shutdown was interrupted; last known up at 2023-01-05 05:19:54 UTC",,,,,,,,,"steampipe","startup",,0
2023-01-05 10:13:06.514 UTC,,,174,"127.0.0.1:37261",63b6a2b2.ae,1,"",2023-01-05 10:13:06 UTC,,0,LOG,00000,"connection received: host=127.0.0.1 port=37261",,,,,,,,,"steampipe","not initialized",,0
2023-01-05 10:13:06.522 UTC,,,175,"127.0.0.1:39224",63b6a2b2.af,1,"",2023-01-05 10:13:06 UTC,,0,LOG,00000,"connection received: host=127.0.0.1 port=39224",,,,,,,,,"steampipe","not initialized",,0
2023-01-05 10:13:06.528 UTC,"root","py5rv2",175,"127.0.0.1:39224",63b6a2b2.af,2,"",2023-01-05 10:13:06 UTC,,0,FATAL,57P03,"the database system is starting up",,,,,,,,,"steampipe","client backend",,0
2023-01-05 10:13:06.529 UTC,,,176,"127.0.0.1:39226",63b6a2b2.b0,1,"",2023-01-05 10:13:06 UTC,,0,LOG,00000,"connection received: host=127.0.0.1 port=39226",,,,,,,,,"steampipe","not initialized",,0
2023-01-05 10:13:06.529 UTC,"root","py5rv2",176,"127.0.0.1:39226",63b6a2b2.b0,2,"",2023-01-05 10:13:06 UTC,,0,FATAL,57P03,"the database system is starting up",,,,,,,,,"steampipe","client backend",,0
2023-01-05 10:13:06.573 UTC,,,172,,63b6a2b2.ac,2,,2023-01-05 10:13:06 UTC,,0,LOG,00000,"database system was not properly shut down; automatic recovery in progress",,,,,,,,,"steampipe","startup",,0
2023-01-05 10:13:06.644 UTC,,,172,,63b6a2b2.ac,3,,2023-01-05 10:13:06 UTC,,0,LOG,00000,"redo starts at 0/16E4120",,,,,,,,,"steampipe","startup",,0
2023-01-05 10:13:06.645 UTC,,,172,,63b6a2b2.ac,4,,2023-01-05 10:13:06 UTC,,0,LOG,00000,"invalid record length at 0/16FB6C8: wanted 24, got 0",,,,,,,,,"steampipe","startup",,0
2023-01-05 10:13:06.645 UTC,,,172,,63b6a2b2.ac,5,,2023-01-05 10:13:06 UTC,,0,LOG,00000,"redo done at 0/16FB660 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s",,,,,,,,,"steampipe","startup",,0
2023-01-05 10:13:06.652 UTC,,,177,"127.0.0.1:39228",63b6a2b2.b1,1,"",2023-01-05 10:13:06 UTC,,0,LOG,00000,"connection received: host=127.0.0.1 port=39228",,,,,,,,,"steampipe","not initialized",,0
2023-01-05 10:13:06.652 UTC,"root","postgres",177,"127.0.0.1:39228",63b6a2b2.b1,2,"",2023-01-05 10:13:06 UTC,,0,FATAL,57P03,"the database system is starting up",,,,,,,,,"steampipe","client backend",,0
2023-01-05 10:13:06.854 UTC,,,178,"127.0.0.1:39232",63b6a2b2.b2,1,"",2023-01-05 10:13:06 UTC,,0,LOG,00000,"connection received: host=127.0.0.1 port=39232",,,,,,,,,"steampipe","not initialized",,0
2023-01-05 10:13:06.854 UTC,"root","postgres",178,"127.0.0.1:39232",63b6a2b2.b2,2,"",2023-01-05 10:13:06 UTC,,0,FATAL,57P03,"the database system is starting up",,,,,,,,,"steampipe","client backend",,0
2023-01-05 10:13:07.056 UTC,,,179,"127.0.0.1:39250",63b6a2b3.b3,1,"",2023-01-05 10:13:07 UTC,,0,LOG,00000,"connection received: host=127.0.0.1 port=39250",,,,,,,,,"steampipe","not initialized",,0
2023-01-05 10:13:07.056 UTC,"root","postgres",179,"127.0.0.1:39250",63b6a2b3.b3,2,"",2023-01-05 10:13:07 UTC,,0,FATAL,57P03,"the database system is starting up",,,,,,,,,"steampipe","client backend",,0
```

This seems to be related resource pressure, CPU or disk (?), in the VM where the workspace is hosted. There is an increase of this particular error rate when the VM is under pressure.

**Steampipe version (`steampipe -v`)**

Seen from v0.16.x onward.

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**

**Additional context**

**Comment by johnsmyth** [comment] 2023-01-09 21:47
@kaidaguerre - Usually, @vhadianto is then able to manually start the service and it works... I'm not sure if we just need a backoff/retry, or if there is actually a bug somewhere?

**Comment by e-gineer** [comment] 2023-01-10 13:01
Duplicate of #2377

**Closed by e-gineer** 2023-01-10 13:01 UTC
Labels: bug
