### ISSUE TITLE
Make it easier to autocomplete with .inspect

### ISSUE THREAD

**Issue by dboeke** [turbot/steampipe#82] opened 2021-01-27 13:10 UTC
The auto-complete feature works differently with .inspect than with table names in the ui.  When writing a query I can see suggestions for matching tables without using the plugin prefix e.g.

<img width="625" alt="image" src="https://user-images.githubusercontent.com/54130/105994989-5d244e80-6076-11eb-9183-bb6a9bbdcb0e.png">

but doing the same thing with `.inspect {table_name} doesn't work, I need to include the {connection}. to prompt auto-complete:

<img width="625" alt="image" src="https://user-images.githubusercontent.com/54130/105995109-8a70fc80-6076-11eb-8864-f2e9444ad69b.png">

Would be great if it worked consistently, and I like the behavior while doing the select query.

**Comment by kaidaguerre** [comment] 2021-01-28 17:10
this is a duplicate of https://github.com/turbot/steampipe/issues/21

**Closed by kaidaguerre** 2021-01-28 17:10 UTC
Labels: enhancement
