### ISSUE TITLE
`mod install` and `mod update` run to completion even if there are unsatisfied requirements

### ISSUE THREAD

**Issue by binaek** [turbot/steampipe#3291] opened 2023-04-03 09:59 UTC
Steampipe mods have requirements for minimum steampipe version and plugin versions. In installations where these requirements are unsatisfied, `mod install` and `mod update` should fail.

**Comment by kaidaguerre** [comment] 2023-04-06 10:47
duplicate of https://github.com/turbot/steampipe/issues/3041

**Closed** 2023-04-06 10:51 UTC
Labels: bug
